### PR TITLE
Nemo palindrome

### PR DESCRIPTION
**Pull request by Nemo652**

### CODE REVIEW

**Comment by Nemo652** [comment]
Please accept this pull request fast.

**Comment by georgekaabraham** [comment]
> Please accept this pull request fast.

Verification done...
Merging now

**Comment by Nemo652** [comment]
I will upload another PR now can you merge it now itself

**Comment by georgekaabraham** [comment]
> I will upload another PR now can you merge it now itself

* Push it, we will review it and accept.

@Nemo652  Thank You for Contributing with us ❤

**Pull request merged**
